### ISSUE TITLE
Fails to build with GHC 7.10.1 – ambiguous type variables

### ISSUE THREAD

**Issue by ehamberg** [zmthy/http-media#13]
Here's the output from an attempted build of `http-media` with GHC 7.10.1:

    src/Network/HTTP/Media/MediaType.hs:97:27:
        No instance for (Foldable t0) arising from a use of ‘notElem’
        The type variable ‘t0’ is ambiguous
        Note: there are several potential instances:
          instance Foldable (Control.Applicative.Const m)
            -- Defined in ‘Control.Applicative’
          instance Foldable (Either a) -- Defined in ‘Data.Foldable’
          instance Foldable Data.Proxy.Proxy -- Defined in ‘Data.Foldable’
          ...plus six others
        In the first argument of ‘ensure’, namely ‘(`notElem` ",;")’
        In the second argument of ‘(.)’, namely ‘ensure (`notElem` ",;")’
        In the expression: CI.mk . ensure (`notElem` ",;")
    
    src/Network/HTTP/Media/MediaType.hs:97:37:
        No instance for (Data.String.IsString (t0 Char))
          arising from the literal ‘",;"’
        The type variable ‘t0’ is ambiguous
        Note: there are several potential instances:
          instance (Data.String.IsString s, CI.FoldCase s) =>
                   Data.String.IsString (CI s)
            -- Defined in ‘case-insensitive-1.2.0.4:Data.CaseInsensitive.Internal’
          instance Data.String.IsString [Char] -- Defined in ‘Data.String’
        In the second argument of ‘notElem’, namely ‘",;"’
        In the first argument of ‘ensure’, namely ‘(`notElem` ",;")’
        In the second argument of ‘(.)’, namely ‘ensure (`notElem` ",;")’

**Comment by purefn** [comment]
I ran into this today too. I have a patch https://github.com/purefn/http-media/commit/bd27134a09d70fa1698fff263ab3e01e167137ca, but the bigger problem is that the tests have a dependency on cabal-test-quickcheck which has an upper limit on base of <4.8.

**Comment by zmthy** [comment]
I patched it early today. I'll release it now.
