### ISSUE TITLE
one test failed with stackage nightly ghc-7.10.2

### ISSUE THREAD

**Issue by juhp** [zmthy/http-media#16]
Not sure if this is due to the change to ghc-7.10.2
but one of the tests for http-media-0.6.2 failed like this:

```
Media:
  parseQuality:
    Without quality: [OK, passed 100 tests]
    With quality: [OK, passed 100 tests]
    With extensions: [OK, passed 100 tests]
  matchAccept:
    Highest quality: [OK, passed 100 tests]
    Most specific: [OK, passed 100 tests]
    Nothing: [Failed]
*** Failed! Falsifiable (after 2 tests):
(used seed 6944558893301243320)
    Never chooses q=0: [OK, passed 100 tests]
    Left biased: [OK, passed 100 tests]
    Against */*: [OK, passed 100 tests]
    Against type/*: [OK, passed 100 tests]
```

while trying to build today Stackage nightly

**Comment by zmthy** [comment]
Sorry, I somehow missed this issue when it was raised.

This was the result of filtering out media types in the wrong direction in the test, allowing for a rare case where the test would generate matching inputs. The tests have been updated to print out the counter-examples in cases like these, and the filtering is now correct.
