### ISSUE TITLE
Parse error on empty param

### ISSUE THREAD

**Issue by benweitzman** [zmthy/http-media#17]
> parseAccept "application/json;q" :: Maybe MediaType 
    Just *** Exception: Data.ByteString.tail: empty ByteString

`parseAccept` should return `Nothing` in this situation

**Comment by zmthy** [comment]
Good catch, this is because the `breakChar` utility function assumes that the character it is breaking on will be present.

**Comment by zmthy** [comment]
Fixed in 0.6.3.
