### ISSUE TITLE
Please include Changelog.

### ISSUE THREAD

**Issue by phadej** [zmthy/http-media#23]
Especially, what are the changes between 0.6 and 0.7?

**Comment by zmthy** [comment]
Good call. I've just started including some [release notes along with tags](https://github.com/zmthy/http-media/releases), I'll put that into an initial changelog.

**Comment by zmthy** [comment]
Done, back to version 0.6.0. I've just pushed a new version that fixes the bounds on base, and the changelog is now included on Hackage. http://hackage.haskell.org/package/http-media-0.7.1/changelog

**Comment by phadej** [comment]
Thanks! A small nitpick, from a user of you library (`servant` depends on your libraryt)
I wish you'd follow PVP (https://pvp.haskell.org/) semantics in your version bumps:

Your version bumps are "too big". Based on the changelog
- `0.6.4 -> 0.7.0` could have been `-> 0.6.5`, as there isn't breaking change. Users of older compile won't be able to upgrade, but they won't get any compile-time or semantic errors.
- Also `0.7.0 -> 0.7.1` could have been `0.7.0.1` to indicate there *are not* semantic changes.

FWIW, the `0.7.1` release won't be needed at all, as Herbert kindly made a revision for `0.7.0`. Note, it's important to do the revision, because dependency solver would pick `0.7.0` with base from `GHC-7.6`. The existence of newer package in the series doesn't force solver to pick it (solver tries to though).

Also the `0.7.0` version bump caused a little of busy-work (for me as `servant` maintainer), as there weren't actual breaking changes.

---

A bigger nitpick: It's very unfortunate you moved to use only Stackage snapshots. (They are *Stackage*, not *stack* snapshots - you can use *Stackage* with cabal-install!)

Because now it's HARD for you to test upcoming GHC releases (GHC-8.2). You cannot test `http-media` in CI against 8.2 before nightly moves to GHC-8.2, but nightly cannot move to newer compiler before packages have support!

`servant` has a `stack.yaml` for GHC-8.2 (rc2 though atm), please consider similar to your CI setup.
https://github.com/haskell-servant/servant/blob/master/stack-ghc-8.2.1.yaml `servant` is already GHC-8.2 ready. As is your package, but not the latest version. Check matrix:

- https://matrix.hackage.haskell.org/package/http-media
- https://matrix.hackage.haskell.org/package/servant

![screen shot 2017-07-15 at 11 32 03](https://user-images.githubusercontent.com/51087/28237890-5c6ddc1a-6951-11e7-958e-c4662d3e7ddb.png)
![screen shot 2017-07-15 at 11 32 29](https://user-images.githubusercontent.com/51087/28237891-5da7bbf0-6951-11e7-8fed-3c45e2bece6a.png)

---

1. *Breaking change*. If any entity was removed, or the types of any entities or the definitions of datatypes or classes were changed, or orphan instances were added or any instances were removed, then the new A.B **MUST** be greater than the previous A.B. Note that modifying imports or depending on a newer version of another package may cause extra orphan instances to be exported and thus force a major version change.

2. *Non-breaking change**. Otherwise, if only new bindings, types, classes, non-orphan instances or modules (but see below) were added to the interface, then A.B *MAY* remain the same but the new C **MUST** be greater than the old C. Note that modifying imports or depending on a newer version of another package may cause extra non-orphan instances to be exported and thus force a minor version change.

3 *Other changes*. Otherwise, e.g. if change consist only of corrected documentation, non-visible change to allow different dependency range etc. A.B.C *MAY* remain the same (other version components may change).

**Comment by zmthy** [comment]
> Your version bumps are "too big".

I'm preparing a 1.0 release, and wanted to put out a new major version to pick out precisely these sorts of problems before dropping the 0 prefix. Sorry for making work for you, but if I can get these problems solved now then it should make everything easier going forward.

> A bigger nitpick: It's very unfortunate you moved to use only Stackage snapshots.

Thanks, I wasn't aware of the limitation of testing against upcoming GHC releases. I'll correct that.
