### ISSUE TITLE
Release master?

### ISSUE THREAD

**Issue by fisx** [zmthy/http-media#35]
It would help with making `servant-*` packages work with ghc8.10.

Thanks!  :)

**Comment by zmthy** [comment]
The most recent changes to the dependencies are available as a revision of 0.8.0.0:

https://hackage.haskell.org/package/http-media-0.8.0.0/revisions/

**Comment by fisx** [comment]
oops, sorry.

I passionately hate revisions...  :-)  but i'll figure it out.

thanks!
