### ISSUE TITLE
Accept-Charset and Accept-Encoding support

### ISSUE THREAD

**Issue by purefn** [zmthy/http-media#4]
Support for `Accept-Charset` and `Accept-Encoding` parsing and choosing would be really useful to me.

**Comment by zmthy** [comment]
This is the purpose of allowing matching on ordinary `ByteString`s, though I've realised that this doesn't support the `*` pattern (and doesn't handle cases like defaulting to `ISO-8859-1` or `identity`). Is this the sort of functionality you're looking for?

**Comment by purefn** [comment]
Just supporting ordinary `ByteStrings1 isn't quite enough.  If support was
also added for `CI ByteString` that would be sufficient.

**Comment by zmthy** [comment]
The case-insensitive matching is now available. I want to add proper matching and defaults for these data types though.

**Comment by zmthy** [comment]
This was added a while ago in [0.8.0.0](https://github.com/zmthy/http-media/releases/tag/v0.8.0.0).
