### ISSUE TITLE
Test suite compiles with "Stub" postfix

### ISSUE THREAD

**Issue by purefn** [zmthy/http-media#6]
When nix tries to build http-media, we see the following error

```
In-place registering test-http-media-0.4.0...
[1 of 1] Compiling Main             ( dist/build/test-http-mediaStub/test-http-mediaStub-tmp/test-http-mediaStub.hs, dist/build/test-http-mediaStub/test-http-mediaStub-tmp/Main.dyn_o )
Linking dist/build/test-http-mediaStub/test-http-mediaStub ...
ghc: panic! (the 'impossible' happened)
  (GHC version 7.8.4 for x86_64-unknown-linux):
	Don't understand library name test-http-media

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

builder for ‘/nix/store/sw1kfp4ryf8zv8bqq58c40fhxkgyh9fd-haskell-http-media-0.4.0.drv’ failed with exit code 1
```

Any idea why the tests get compiled as `test-http-mediaStub` instead of `test-http-media`?

**Comment by zmthy** [comment]
I've also been getting errors that have to do with the versioning of Cabal. I'll fiddle with the QuickCheck integration to see if I can get it up to date, and then try again.

**Comment by zmthy** [comment]
The testing is working on my end again. The Stub suffix seems to be standard Cabal behaviour for the detailed-0.9 test framework. If it's still not working for http-media-0.5.0, this should be taken to the Cabal devs.

**Comment by zmthy** [comment]
The latest version no longer uses detailed-0.9 for testing, so you shouldn't see this problem anymore.
