### ISSUE TITLE
Identical media types with whitespace in parameters fail to match

### ISSUE THREAD

**Issue by ehamberg** [zmthy/http-media#7]
The following code should succeed, but returns `Nothing`:

    λ> matchAccept ["application/json; charset=utf-8"] "application/json; charset=utf-8" :: Maybe MediaType
    Nothing
However, if you remove the space after the semicolon, it succeeds:

    λ> matchAccept ["application/json;charset=utf-8"] "application/json;charset=utf-8" :: Maybe MediaType
    Just application/json;charset=utf-8

It looks like this might be related to the library not ignoring whitespace in the parameters:

    λ> parameters "application/json; charset=utf-8"
    fromList [(" charset","utf-8")]

**Comment by zmthy** [comment]
Fixed with 0.5.0 release.
