### ISSUE TITLE
Comparison of `charset` parameter's should be case-insensitive

### ISSUE THREAD

**Issue by ehamberg** [zmthy/http-media#8]
As specified in [1], names for character encodings are case-insensitive. So comparison of `charset` values should be special-cased to not take case into account. In the current version of the library, there is no special handling of `charset`, so the following fails:

    λ> matchAccept ["application/json;charset=utf-8"] "application/json;charset=UTF-8" :: Maybe MediaType
    Nothing

[1] http://www.w3.org/TR/html4/charset.html#h-5.2.1

**Comment by zmthy** [comment]
This is related to #5. I think it's sensible to just match everything in a case-insensitive manner.

**Comment by zmthy** [comment]
Fixed with 0.5.0 release.
